### ISSUE TITLE
Error: Can't find variable: google

### ISSUE THREAD

**Issue by lifeisfunny** [zenvisuals/ionic-angular-google-maps#2]
$scope.options = {scrollwheel: false,mapTypeId: google.maps.MapTypeId.ROADMAP };
When try to define the maptypeId  , warning Cant find variable: google show up !

**Comment by zenvisuals** [comment]
Hi @lifeisfunny,

The google SDK is not loaded into the application, which is why the SDK is not found (Cant find variable: google). There are two ways to solve this issue. You may either:

1) Include Google Maps SDK in your application in your index.html

<script src="https://maps.googleapis.com/maps/api/js?sensor=false" type="text/javascript"></script>

2) In google.maps.MapTypeId, it is an object of constants mapping to string values

``` javascript
google.maps.MapTypeId = {
    HYBRID: "hybrid",
    ROADMAP: "roadmap",
    SATELLITE: "satellite",
    TERRAIN: "terrain"
}
```

Simply just append the string value to your options instead of referencing them to the constant should work fine.
E.g: 

``` javascript
$scope.options = {scrollwheel: false,mapTypeId: "satellite" };
```
